### ISSUE TITLE
Select minimum Python version

### ISSUE THREAD

**Issue by dorbarker** [WGS-standards-and-analysis/standard-measurements#1]
A particular minimum Python version should probably be specified before 2-_vs_-3 incompatibilities start cropping up.

3.7 is the current stable version per python.org
3.6 is what's shipping on recent editions of Ubuntu/Debian

I'd argue in favour of >=3.5, as that's the oldest version receiving bug fixes. 

That being said, at the time of this comment, N50.py is written for 2.7.

**Comment by lskatz** [comment]
Thank you for that idea @dorbarker!  I will opt to keep with the current stable version of Python, 3.7 to help keep us future-resistant, and I marked it in the documentation in 4329b27ac5866e5c2f88ef9f9235ad15edd6e905.  I fixed `N50.py` in 6fcd1cfc7dc6a614c8c4286a92a6f6616bc6908c so that it is compatible with v3.7, per your suggestion..
